name: RENATE-OD CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9.12', '3.11.17']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        status=0
        for t in \
            crm_solver.odetest.OdeTest \
            crm_solver.crmsystemtest.CrmRegressionTest \
            crm_solver.crmsystemtest.CrmAcceptanceTest \
            crm_solver.beamlettest.BeamletTest \
            crm_solver.coefficientmatrixtest.CoefficientMatrixTest \
            atomic.atomic_dbtest.AtomicDBTest \
            atomic.toolstest.AtomicDB_to_HDF_WriterTest \
            atomic.atomic_dbtest.RenateDBTest \
            atomic.neutral_dbtest.NeutralDBTest \
            utility.accessdatatest.AccessDataTest \
            utility.converttest.ConvertTest \
            utility.getdatatest.GetDataTest \
            utility.putdatatest.PutDataTest \
            utility.managetest.VersionTest \
            utility.managetest.CodeInfoTest \
            utility.inputtest.AtomicInputTest \
            utility.inputtest.BeamletInputTest \
            utility.writedatatest.WriteDataTest \
            observation.noisetest.NoiseGeneratorTest \
            observation.noisetest.APDGeneratorTest \
            observation.noisetest.PMTGeneratorTest \
            observation.noisetest.PPDGeneratorTest \
            observation.noisetest.MPPCGeneratorTest \
            observation.noisetest.DetectorGeneratorTest \
            observation.noisetest.NoiseRegressionTest; do
          python -m unittest -v "$t" || status=1
        done
        exit $status

